[package]
name = "aether_graphics"
version = "0.1.1"
edition = "2021"

[features]
default = ["no_std"]
std = []
no_std = []

[lib]
crate-type = ["rlib"]

[dependencies]
num-traits = "0.2"
aether_core = { path = "../aether_core" }
