[package]
name = "aether_units"
edition.workspace = true
license-file.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
aether_core = {path="../aether_core"}

[lints]
workspace = true
