[package]
name = "aether_examples"
version = "0.1.1"
edition = "2021"

[features]
default = ["no_std"]
std = []
no_std = []

[[bin]]
name = "matrix"
path = "src/matrix.rs"

[[bin]]
name = "coordinates"
path = "src/coordinates.rs"

[dependencies]
aether_core = {path = "../aether_core"}
